name: Run Gosec
on:
  push: 
    branches:
      - gotest # for testing this workflow
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run gotest
        run: go test ./...
